document.addEventListener("DOMContentLoaded", function() {
    const languageSelector = document.getElementById("language-selector");
    const privacyPolicy = document.getElementById("privacy-policy");

    const helpContent = {
        en: `
            <h2>Privacy Policy</h2>
            <p>Last Update: 3/10/2023</p>
            <h3>General Information</h3>
            <p>The following Privacy Policy describes how Eloi Mesa ("we," "our," or "Eloi Mesa") protects your privacy while using the FireNotes extension ("the Extension"). We value your privacy and want to ensure you understand how we handle your information when using the Extension. By installing and using the Extension, you agree to the practices described in this Privacy Policy.</p>
            <h3>Internet Connection</h3>
            <p>It is important to note that FireNotes does not connect to the internet. The Extension operates entirely locally in your browser and does not transmit data over the network. This means we do not collect or send personal information to external servers while you use FireNotes.</p>
            <h3>Links to External Websites</h3>
            <p>The Extension may provide links to external websites, including the official FireNotes website and other related resources. Please be aware that these external websites may have different privacy policies than ours. This Privacy Policy exclusively applies to the Extension and does not extend to data collection on third-party websites. We recommend reviewing the privacy policies of these sites before interacting with them.</p>
            <h3>Local Data Storage</h3>
            <p>All data generated by the Extension, such as notes, settings, and preferences, is stored locally in your browser. We do not track or store personal information outside of your device. This ensures that your data remains secure and private, and the Extension functions even without an internet connection.</p>
            <h3>Website Privacy Policy</h3>
            <p>To consult the Privacy Policy of Eloi Mesa's official website, which is independent of the FireNotes Extension Privacy Policy, you can do so through the following link: <a href="https://elmees21.github.io/privacy/" target="_blank">Eloi Mesa's Website Privacy Policy</a>.</p>
            <h3>Contact Us</h3>
            <p>If you have any questions or concerns about our FireNotes Extension Privacy Policy, please do not hesitate to contact us at the following email address: <a href="mailto:eloi.mesa@outlook.com">eloi.mesa@outlook.com</a>.</p>
            <p>Thank you for choosing our FireNotes Extension. We are committed to providing you with a secure and private experience while using our extension in your browser. Your privacy is important to us, and we appreciate your trust in us.</p>
        `,
        es: `
            <h2>Política de Privacidad</h2>
            <p>Última Actualización: 3/10/2023</p>
            <h3>Información General</h3>
            <p>La siguiente Política de Privacidad describe cómo Eloi Mesa ("nosotros", "nuestro" o "Eloi Mesa") protege su privacidad mientras utiliza la extensión de FireNotes ("la Extensión"). Valoramos su privacidad y queremos asegurarnos de que comprenda cómo manejamos su información al utilizar la Extensión. Al instalar y utilizar la Extensión, usted acepta las prácticas descritas en esta Política de Privacidad.</p>
            <h3>Conexión a Internet</h3>
            <p>Es importante destacar que FireNotes no se conecta a internet. La Extensión opera de forma completamente local en su navegador y no realiza ninguna transmisión de datos a través de la red. Esto significa que no recopilamos ni enviamos información personal a servidores externos mientras utiliza FireNotes.</p>
            <h3>Enlaces a Sitios Web Externos</h3>
            <p>La Extensión puede proporcionar enlaces a sitios web externos, incluyendo la página web oficial de FireNotes y otros recursos relacionados. Tenga en cuenta que estos sitios web externos pueden tener políticas de privacidad diferentes a las nuestras. Esta Política de Privacidad se aplica exclusivamente a la Extensión y no se extiende a la recopilación de datos en sitios web de terceros. Le recomendamos revisar las políticas de privacidad de estos sitios antes de interactuar con ellos.</p>
            <h3>Almacenamiento Local de Datos</h3>
            <p>Todos los datos generados por la Extensión, como notas, ajustes y preferencias, se almacenan de forma local en su navegador. No realizamos ningún seguimiento ni almacenamos información personal fuera de su dispositivo. Esto garantiza que sus datos permanezcan seguros y privados, y que la Extensión funcione incluso sin conexión a internet.</p>
            <h3>Política de Privacidad de la Web</h3>
            <p>Para consultar la Política de Privacidad de la página web oficial de Eloi Mesa, que es independiente de la Política de Privacidad de la Extensión de FireNotes, puede hacerlo a través del siguiente enlace: <a href="https://elmees21.github.io/privacy/" target="_blank">Política de Privacidad de la Web de Eloi Mesa</a>.</p>
            <h3>Contáctenos</h3>
            <p>Si tiene alguna pregunta o inquietud sobre nuestra Política de Privacidad de la Extensión de FireNotes, no dude en ponerse en contacto con nosotros a través de la siguiente dirección de correo electrónico: <a href="mailto:eloi.mesa@outlook.com">eloi.mesa@outlook.com</a>.</p>
            <p>Gracias por elegir nuestra Extensión de FireNotes. Estamos comprometidos en brindarle una experiencia segura y privada mientras utiliza nuestra extensión en su navegador. Su privacidad es importante para nosotros y valoramos su confianza en nosotros.</p>
        `,
        ca: `
            <h2>Política de Privacitat</h2>
            <p>Última Actualització: 3/10/2023</p>
            <h3>Informació General</h3>
            <p>La següent Política de Privacitat descriu com Eloi Mesa ("nosaltres", "el nostre" o "Eloi Mesa") protegeix la seva privacitat mentre utilitza l'extensió de FireNotes ("l'Extensió"). Valorem la seva privacitat i volem assegurar-nos que comprengui com gestionem la seva informació en utilitzar l'Extensió. En instal·lar i utilitzar l'Extensió, vostè accepta les pràctiques descrites en aquesta Política de Privacitat.</p>
            <h3>Connexió a Internet</h3>
            <p>És important destacar que FireNotes no es connecta a internet. L'Extensió opera de manera totalment local en el seu navegador i no realitza cap transmissió de dades a través de la xarxa. Això significa que no recopilem ni enviem informació personal a servidors externs mentre utilitza FireNotes.</p>
            <h3>Enllaços a Llocs Web Externs</h3>
            <p>L'Extensió pot proporcionar enllaços a llocs web externs, incloent la pàgina web oficial de FireNotes i altres recursos relacionats. Tingui en compte que aquests llocs web externs poden tenir polítiques de privacitat diferents a les nostres. Aquesta Política de Privacitat s'aplica exclusivament a l'Extensió i no s'estén a la recopilació de dades en llocs web de tercers. Li recomanem revisar les polítiques de privacitat d'aquests llocs abans d'interactuar amb ells.</p>
            <h3>Emmagatzematge Local de Dades</h3>
            <p>Totes les dades generades per l'Extensió, com ara notes, ajustos i preferències, s'emmagatzemen de manera local al seu navegador. No realitzem cap seguiment ni emmagatzemem informació personal fora del seu dispositiu. Això garanteix que les seves dades romanguin segures i privades, i que l'Extensió funcioni fins i tot sense una connexió a internet.</p>
            <h3>Política de Privacitat del Lloc Web</h3>
            <p>Per consultar la Política de Privacitat del lloc web oficial d'Eloi Mesa, que és independent de la Política de Privacitat de l'Extensió de FireNotes, pot fer-ho a través de l'enllaç següent: <a href="https://elmees21.github.io/privacy/" target="_blank">Política de Privacitat del Lloc Web d'Eloi Mesa</a>.</p>
            <h3>Contacti'ns</h3>
            <p>Si té alguna pregunta o preocupació sobre la nostra Política de Privacitat de l'Extensió de FireNotes, no dubti a posar-se en contacte amb nosaltres a través de la següent adreça de correu electrònic: <a href="mailto:eloi.mesa@outlook.com">eloi.mesa@outlook.com</a>.</p>
            <p>Gràcies per triar la nostra Extensió de FireNotes. Estem compromesos a proporcionar-li una experiència segura i privada mentre utilitza la nostra extensió al seu navegador. La seva privacitat és important per a nosaltres i valorem la seva confiança en nosaltres.</p>
        `,
        it: `
            <h2>Informativa sulla Privacy</h2>
            <p>Ultimo Aggiornamento: 3/10/2023</p>
            <h3>Informazioni Generali</h3>
            <p>La seguente Informativa sulla Privacy descrive come Eloi Mesa ("noi," "nostro," o "Eloi Mesa") protegge la tua privacy durante l'utilizzo dell'estensione FireNotes ("l'Estensione"). Valorizziamo la tua privacy e vogliamo assicurarci che tu comprenda come trattiamo le tue informazioni quando utilizzi l'Estensione. Installando e utilizzando l'Estensione, accetti le pratiche descritte in questa Informativa sulla Privacy.</p>
            <h3>Connessione a Internet</h3>
            <p>È importante sottolineare che FireNotes non si connette a internet. L'Estensione opera interamente localmente nel tuo browser e non trasmette dati sulla rete. Ciò significa che non raccogliamo o inviamo informazioni personali a server esterni mentre utilizzi FireNotes.</p>
            <h3>Collegamenti a Siti Web Esterni</h3>
            <p>L'Estensione potrebbe fornire collegamenti a siti web esterni, inclusi il sito web ufficiale di FireNotes e altre risorse correlate. Tieni presente che questi siti web esterni potrebbero avere politiche sulla privacy diverse dalle nostre. Questa Informativa sulla Privacy si applica esclusivamente all'Estensione e non si estende alla raccolta di dati su siti web di terze parti. Ti consigliamo di revisionare le politiche sulla privacy di questi siti prima di interagire con essi.</p>
            <h3>Archiviazione Locale dei Dati</h3>
            <p>Tutti i dati generati dall'Estensione, come note, impostazioni e preferenze, vengono archiviati localmente nel tuo browser. Non tracciamo né archiviamo informazioni personali al di fuori del tuo dispositivo. Ciò garantisce che i tuoi dati rimangano sicuri e privati, e che l'Estensione funzioni anche senza una connessione a internet.</p>
            <h3>Informativa sulla Privacy del Sito Web</h3>
            <p>Per consultare l'Informativa sulla Privacy del sito web ufficiale di Eloi Mesa, che è indipendente dall'Informativa sulla Privacy dell'Estensione FireNotes, puoi farlo tramite il seguente link: <a href="https://elmees21.github.io/privacy/" target="_blank">Informativa sulla Privacy del Sito Web di Eloi Mesa</a>.</p>
            <h3>Contattaci</h3>
            <p>Se hai domande o preoccupazioni sulla nostra Informativa sulla Privacy dell'Estensione FireNotes, non esitare a contattarci al seguente indirizzo email: <a href="mailto:eloi.mesa@outlook.com">eloi.mesa@outlook.com</a>.</p>
            <p>Grazie per aver scelto la nostra Estensione FireNotes. Siamo impegnati a offrirti un'esperienza sicura e privata durante l'utilizzo della nostra estensione nel tuo browser. La tua privacy è importante per noi e apprezziamo la tua fiducia in noi.</p>
        `,
    };

    // Function to change language and load the corresponding help content
    languageSelector.addEventListener("change", function() {
        const selectedLanguage = languageSelector.value;
        privacyPolicy.innerHTML = helpContent[selectedLanguage];
    });

    // Initial call to load help content in English if the user's language is not available
    const userLanguage = navigator.language.split('-')[0];
    if (helpContent[userLanguage]) {
        languageSelector.value = userLanguage;
        privacyPolicy.innerHTML = helpContent[userLanguage];
    } else {
        privacyPolicy.innerHTML = helpContent["en"]; // Load English by default
    }
});

// Function to go back in the browser's history
function goBack() {
    window.history.back();
}
